# Global configuration
required_skills_match_threshold: 0.85  # Increased from 0.75 to ensure stronger skill matches

# Analysis patterns for matching
analysis_patterns:
  experience:
    - '(\d+)\+?\s*years?.+experience'
    - '(\d+)\+?\s*years?.+industry'
    - 'experience\D*(\d+)\+?\s*years?'
    - 'career\s+spanning\D*(\d+)\+?\s*years?'
    - 'with\s+(\d+)\+?\s*years?\s+(?:of\s+)?experience'
    - '(\d+)\+?\s*years?\s+(?:of\s+)?experience\s+in'

  skills:
    python: '\b(?:python|py3?|python[23]|pandas|numpy|django|flask|pypi|python-based)\b(?:\s*(?:development|programming|coding|experience|engineer|developer|skilled at|skilled|programming|coding|development|engineering|packages?|tools?|managers?))?'
    javascript: '\b(?:javascript|js|node(?:\.?js)?|react|angular|vue(?:\.?js)?|typescript|es6)\b(?:\s*(?:languages?|skills?|tech(?:nolog(?:y|ies))?|stack|proficien(?:t|cy)|expertise|knowledge|background|development|programming|coding|experience|engineer|developer|skilled|programming|coding|development|engineering))*'
    git: '\b(?:git(?:hub|lab)?|version\s*control|source\s*control)\b'
    sql: '\b(?:sql|mysql|postgresql|postgres|oracle|sqlite|mssql)\b'
    nosql: '\b(?:nosql|mongodb|mongo|dynamodb|cassandra|redis|elasticsearch)\b'
    data_structures: '\b(?:data\s*structures?|algorithms?|algorithm\s*design|optimization)\b'
    algorithms: '\b(?:algorithms?|algorithm\s*design|computational|complexity|optimization)\b'
    ci_cd: '\b(?:ci(?:/|_|\s+)?cd|continuous\s*(?:integration|deployment|delivery)|jenkins|circleci|github\s*actions)\b'
    system_design: '\b(?:system\s*design|architecture|distributed\s*systems?|scalable\s*systems?|high\s*availability)\b'
    django: '\b(?:django|drf|django\s*rest\s*framework)\b'
    nodejs: '\b(?:node(?:\.?js)?|express(?:\.?js)?|npm)\b'
    graphql: '\b(?:graphql|graph\s*ql|apollo)\b'
    rest_apis: '\b(?:rest\s*apis?|restful|api\s*development|web\s*services)\b'
    aws: '\b(?:aws|amazon\s*web\s*services|ec2|s3|rds|lambda|cloudwatch|ecs|ecr)\b'
    circleci: '\b(?:circleci|circle\s*ci)\b'
    docker: '\b(?:docker|containerization|containers?)\b'
    kubernetes: '\b(?:kubernetes|k8s|container\s*orchestration)\b'
    react: '\b(?:react(?:\.?js)?|reactjs|react\s*native)\b'
    vuejs: '\b(?:vue(?:\.?js)?|vuejs|vuex)\b'

  context:
    - 'developed'
    - 'implemented'
    - 'architected'
    - 'designed'
    - 'automated'
    - 'optimized'
    - 'managed'
    - 'deployed'
    - 'experience'
    - 'development'
    - 'proficient'
    - 'expertise'
    - 'programming'
    - 'coding'
    - 'engineer'
    - 'developer'
    - 'worked'
    - 'using'
    - 'familiar'
    - 'knowledge'
    - 'built'
    - 'created'
    - 'maintained'
    - 'languages'
    - 'skills'
    - 'technical'
    - 'stack'
    - 'tools'
    - 'skilled'

# Enhanced scoring configuration
scoring_config:
  weights:
    technical:
      skills: 0.40
      platform_specific_experience: 0.15
      experience: 0.35
      role_relevance: 0.10

  thresholds:
    strong_match: 85
    good_match: 70
    potential_match: 50
    minimum_match: 30

  skill_weights:
    required: 0.75
    preferred: 0.25

# Job role definitions
job_roles:
  "Data Scientist":
    role_type: technical
    education:
      minimum: "Bachelor's degree"
      preferred: "Master's or Doctoral degree"
      fields:
        - "Computer Science"
        - "Electrical Engineering"
        - "Statistics"
        - "Related fields"
    scoring_weights: technical
    min_years_experience: 5
    scoring_constraints:
      max_score: 100
      required_skills_threshold: 0.70
      minimum_skills_match: 0.60
    required_skills:
      - Python
      - Machine Learning
      - Statistics
      - Data Visualization
      - Git
      - "Linear Algebra OR Probability"
    preferred_skills:
      - TensorFlow
      - PyTorch
      - Scikit-learn
      - Pandas
      - NumPy
      - Deep Learning
      - LangChain
      - Docker
      - Kubernetes
      - MLflow
      - Databricks
      - MapReduce
      - Streaming Technology
    skill_weights:
      core_ml: 0.30
      math: 0.25
      data_tools: 0.25
      devops: 0.20
    skill_groups:
      core_ml:
        - Machine Learning
        - Deep Learning
        - TensorFlow
        - PyTorch
      math:
        - Statistics
        - Linear Algebra
        - Probability
      data_tools:
        - Python
        - Pandas
        - NumPy
        - Data Visualization
      devops:
        - Git
        - Docker
        - Kubernetes
    key_responsibilities:
      - Collaborate with internal and external teams
      - Develop and test machine learning models
      - Deploy and optimize ML solutions
      - Create application specifications and documentation
      - Troubleshoot performance issues
      - Transform data into business intelligence
    soft_skills:
      - Strong verbal communication
      - Strong written communication
      - Self-driven
      - Project leadership
      - Independent work capability
      - Team collaboration

  "Software Development Engineer, C3":
    role_type: technical
    education:
      minimum: "Bachelor's degree"
      fields:
        - "Computer Science"
        - "Related fields"
        - "Equivalent combination of education and experience"
    scoring_weights: technical
    min_years_experience: 5
    scoring_constraints:
      max_score: 100
      required_skills_threshold: 0.60
      minimum_skills_match: 0.50
    required_skills:
      - Python
      - JavaScript
      - Git
      - SQL
      - NoSQL
      - Data Structures
      - Algorithms
      - CI/CD
      - System Design
    preferred_skills:
      - Django
      - Node.js
      - GraphQL
      - REST APIs
      - AWS
      - CircleCI
      - Docker
      - Kubernetes
      - React
      - Vue.js
    skill_weights:
      frontend: 0.40
      backend: 0.30
      devops: 0.20
      core_cs: 0.10
    skill_groups:
      frontend:
        - React
        - JavaScript
        - Redux
        - TypeScript
        - Vue.js
        - Angular
      backend:
        - Python
        - SQL
        - NoSQL
        - REST APIs
      devops:
        - Git
        - CI/CD
        - GitLab
        - Shell Scripting
      core_cs:
        - Data Structures
        - Algorithms
    key_responsibilities:
      - Develop and maintain web applications
      - Collaborate with cross-functional teams
      - Implement responsive user interfaces
      - Optimize application for performance and scalability
      - Ensure code quality through testing and code reviews
      - Troubleshoot and debug production issues
    soft_skills:
      - Strong problem-solving skills
      - Excellent communication skills
      - Ability to work independently
      - Attention to detail
      - Continuous learning mindset
      - Adaptability in fast-paced environments
    skill_variations:
      python: ['python', 'py', 'py3', 'python3', 'python2', 'pandas', 'numpy', 'django', 'flask']
      javascript: ['javascript', 'js', 'node.js', 'nodejs', 'react', 'angular', 'vue', 'typescript', 'es6']
      git: ['git', 'github', 'gitlab', 'version control', 'source control']
      sql: ['sql', 'mysql', 'postgresql', 'postgres', 'oracle', 'sqlite', 'mssql']
      nosql: ['nosql', 'mongodb', 'mongo', 'dynamodb', 'cassandra', 'redis', 'elasticsearch']
      data_structures: ['data structures', 'datastructures', 'data-structures', 'algorithms', 'algorithm design']
      algorithms: ['algorithms', 'algorithm design', 'computational', 'complexity', 'optimization']
      ci_cd: ['ci/cd', 'continuous integration', 'continuous deployment', 'jenkins', 'circleci', 'github actions']
      system_design: ['system design', 'architecture', 'distributed systems', 'scalable systems', 'high availability']
      django: ['django', 'drf', 'django rest framework']
      node_js: ['node.js', 'nodejs', 'express', 'npm']
      graphql: ['graphql', 'graph ql', 'apollo']
      rest_apis: ['rest apis', 'restful', 'api development', 'web services']
      aws: ['aws', 'amazon web services', 'ec2', 's3', 'rds', 'lambda', 'cloudwatch', 'ecs', 'ecr']
      circleci: ['circleci', 'circle ci']
      docker: ['docker', 'containerization', 'containers']
      kubernetes: ['kubernetes', 'k8s', 'container orchestration']
      react: ['react', 'reactjs', 'react native']
      vue_js: ['vue.js', 'vuejs', 'vue', 'vuex']

  "DevOps Engineer":
    role_type: technical
    education:
      minimum: "Bachelor's degree"
      fields:
        - "Computer Science"
        - "Information Technology"
        - "Related fields"
        - "Equivalent combination of education and experience"
    scoring_weights: technical
    min_years_experience: 3
    scoring_constraints:
      max_score: 100
      required_skills_threshold: 0.60
      minimum_skills_match: 0.50
    required_skills:
      - Linux
      - Python OR Ruby
      - AWS OR GCP OR Azure
      - Kubernetes
      - CI/CD
      - Infrastructure as Code
      - Networking
      - Database Management
      - NoSQL
      - Cassandra
      - Ansible OR Terraform
    preferred_skills:
      - Docker
      - Jenkins
      - GitOps
      - CI/CD
      - Prometheus
      - Grafana
      - ELK Stack
      - Istio
      - Groovy
      - Bash
      - CloudFormation
    skill_weights:
      infrastructure: 0.30
      cloud_platforms: 0.25
      automation: 0.25
      monitoring: 0.20
    skill_groups:
      infrastructure:
        - Linux
        - Kubernetes
        - Docker
        - Networking
        - Database Management
      cloud_platforms:
        - AWS
        - GCP
        - Azure
      automation:
        - Python
        - Ruby
        - Ansible
        - Terraform
        - CI/CD
      monitoring:
        - Prometheus
        - Grafana
        - ELK Stack
    key_responsibilities:
      - "Ensure maximum system uptime and availability"
      - "Implement end-to-end monitoring and alerting"
      - "Resolve complex technical issues"
      - "Develop resilient system architectures"
      - "Lead automation initiatives"
      - "Design and configure infrastructure"
      - "Collaborate with Services and Engineering teams"
    soft_skills:
      - "Problem-solving abilities"
      - "Critical thinking"
      - "Strong communication"
      - "Cross-functional collaboration"
      - "System administration"
      - "DevOps practices"

  "Generative AI Architect":
    role_type: technical
    scoring_weights: technical
    min_years_experience: 8
    scoring_constraints:
      max_score: 100
      required_skills_threshold: 0.7
    required_skills:
      - MLOps
      - AI Architecture
      - Containerization
      - Model Optimization
      - Python
      - Cloud Platforms (GCP, AWS, Azure)
    preferred_skills:
      - OpenAI API
      - TensorFlow
      - PyTorch
      - RLHF
      - Data Science
      - ETL Pipeline Management
      - Kubernetes