llm_config:
  response_format:
    schema: {
      "technical_match_score": "integer between 0-100",
      "recommendation": "one of: STRONG_MATCH, GOOD_MATCH, POTENTIAL_MATCH, NO_MATCH",
      "interview_questions": [
        {
          "category": "string (Technical Implementation|Experience Translation|Skill Gaps)",
          "question": "detailed multi-part question",
          "context": "relevant context from resume"
        }
      ],
      "technical_gaps": ["list of missing or weak skills"],
      "key_findings": ["list of important observations"],
      "concerns": ["list of potential issues"],
      "confidence_score": "overall confidence in analysis (0-1)"
    }
  system_prompt: |
    You are a technical resume analyzer. Your task is to analyze resumes and return ONLY a JSON response matching the provided schema.
    
    Important rules:
    1. Return ONLY the JSON object
    2. Do not include any explanatory text
    3. Do not use markdown formatting
    4. Ensure all JSON keys and values match the schema exactly
    5. Use proper JSON formatting with double quotes for strings
    6. Do not include trailing commas
    7. Always include all required fields
    8. Use null for missing optional values
    9. Format numbers without quotes
    10. Use proper boolean values (true/false) without quotes

  user_prompt_template: |
    Analyze this resume for {role} position:

    Resume Text:
    {resume_text}

    Job Requirements:
    - Required Skills: {required_skills}
    - Preferred Skills: {preferred_skills}
    - Minimum Experience: {min_years} years

    {skills_context}
    {experience_context}

analysis_patterns:
  experience:
    - '(\d+)\+?\s*(?:years?|yrs?)(?:\s+of)?\s+(?:experience|work|professional|research)'
    - 'experience\s+of\s+(\d+)\+?\s*(?:years?|yrs?)'
    - '(?:since|from)\s+(\d{4})'
    - '(\d{4})\s*-\s*(?:present|current|now)'
  context:
    - 'developed'
    - 'implemented'
    - 'architected'
    - 'designed'
    - 'built'
    - 'created'
    - 'managed'
    - 'led'
    - 'coordinated'
    - 'analyzed'
  location:
    US: '(?:United States|USA|U\.S\.A\.|US|California|New York|Texas)'
    non-US: '(?:India|China|Europe|Asia|Africa|South America)'

experience_types:
  professional:
    - 'Senior'
    - 'Lead'
    - 'Staff'
    - 'Principal'
    - 'Architect'
    - 'Manager'
    - 'Engineer'
    - 'Developer'
  internship:
    - 'Intern'
    - 'Internship'
    - 'Co-op'
    - 'Trainee'
  academic:
    - 'Research'
    - 'Project'
    - 'Thesis'
    - 'Academic'
    - 'Course'
    - 'Study'

scoring_config:
  semantic_threshold: 0.45
  experience_weights:
    us_experience: 1.0
    non_us_experience: 0.6
    professional: 1.0
    internship: 0.25
    academic: 0.15

skill_variations:
  python:
    aliases: ['py', 'python3', 'python2', 'pythonic']
    forms: ['programming', 'development', 'scripting']
  javascript:
    aliases: ['js', 'es6', 'ecmascript', 'node.js', 'nodejs']
    forms: ['frontend', 'backend', 'fullstack']
  java:
    aliases: ['core java', 'j2ee', 'jvm']
    forms: ['backend', 'enterprise']

job_roles:
  Data Scientist:
    required_skills:
      - Python
      - Machine Learning
      - Data Analysis
      - Statistics
      - SQL
    preferred_skills:
      - Deep Learning
      - TensorFlow/PyTorch
      - Big Data
      - Cloud Platforms
      - Data Visualization
    
  Software Development Engineer:
    required_skills:
      - Java/Python/C++
      - Data Structures
      - Algorithms
      - System Design
      - Git
    preferred_skills:
      - Cloud Services
      - Microservices
      - CI/CD
      - Testing
      - Agile

  Full Stack Software Engineer:
    required_skills:
      - JavaScript/TypeScript
      - React/Angular/Vue
      - Node.js
      - SQL/NoSQL
      - RESTful APIs
    preferred_skills:
      - Cloud Platforms
      - DevOps
      - GraphQL
      - Docker
      - Web Security

  UI Designer:
    required_skills:
      - UI/UX Design
      - Figma/Sketch
      - HTML/CSS
      - Design Systems
      - Prototyping
    preferred_skills:
      - User Research
      - Motion Design
      - Adobe Creative Suite
      - Design Thinking
      - Accessibility

  Engagement Manager:
    required_skills:
      - Project Management
      - Client Relations
      - Team Leadership
      - Communication
      - Problem Solving
    preferred_skills:
      - Agile/Scrum
      - Risk Management
      - Business Analysis
      - Change Management
      - Stakeholder Management

  ML Ops Engineer:
    required_skills:
      - Python
      - Docker
      - Kubernetes
      - CI/CD
      - ML Frameworks
    preferred_skills:
      - Cloud Platforms
      - Monitoring Tools
      - Infrastructure as Code
      - Model Serving
      - Data Pipeline

  Solutions Architect:
    required_skills:
      - System Design
      - Cloud Architecture
      - Security
      - Integration
      - Technical Leadership
    preferred_skills:
      - Multi-cloud
      - Microservices
      - Cost Optimization
      - Performance Tuning
      - Enterprise Architecture

  AWS Platform Data Engineer:
    required_skills:
      - AWS Services
      - Python/Java
      - SQL/NoSQL
      - ETL Pipelines
      - Data Modeling
    preferred_skills:
      - Spark
      - Airflow
      - Terraform
      - Data Lakes
      - Data Warehousing

  Site Reliability Engineer:
    required_skills:
      - Linux/Unix
      - Monitoring
      - Automation
      - Cloud Platforms
      - Incident Response
    preferred_skills:
      - Kubernetes
      - Infrastructure as Code
      - Performance Tuning
      - Security
      - Load Balancing

  Generative AI Architect:
    required_skills:
      - Deep Learning
      - NLP
      - Python
      - LLM Integration
      - Model Deployment
    preferred_skills:
      - Prompt Engineering
      - Model Fine-tuning
      - MLOps
      - Vector Databases
      - RAG Systems

# Interview question templates for different categories
interview_questions:
  technical_implementation:
    - template: "Can you describe how you used {skill} in {context}? What were the specific challenges and how did you overcome them?"
    - template: "Walk me through a specific project where you applied {skill}. What was your role and what was the outcome?"
  skill_depth:
    - template: "You mention extensive experience with {skill} in {context}. Can you elaborate on the most complex problem you solved using this technology?"
    - template: "What are some best practices you've developed while working with {skill} based on {context}?"
  gap_assessment:
    - template: "While you have strong experience in {related_skill}, I notice {missing_skill} isn't mentioned. How would you approach learning and applying this skill?"
    - template: "Can you discuss any indirect experience or transferable skills you have that would help you quickly adapt to working with {missing_skill}?"
  project_impact:
    - template: "During your time at {company}, what was the business impact of your {project} using {skill}?"
    - template: "Can you quantify the results of your work on {project} at {company}?"
  linkedin_verification:
    - template: "Your LinkedIn profile strongly aligns with your resume. Could you elaborate on how you maintain consistency across your professional profiles?"
    - template: "Your LinkedIn endorsements validate your expertise. Can you share a specific example that demonstrates your proficiency?"
  linkedin_discrepancies:
    - template: "I notice some differences between your resume and LinkedIn profile. Could you help me understand these variations?"
    - template: "There are some experiences mentioned in your LinkedIn profile that aren't in your resume. Could you tell me more about your role in these positions?"
